---
- name: Start
  hosts: "{{ target | default('all') }}"
  become: yes
  gather_facts: no

  vars:
    containers:
      - mariadb
      - wordpress
      - phpmyadmin
      - nginx

  tasks:
    - name: Start containers
      docker_container:
        name: "{{ item }}"
      loop: "{{ containers }}"
